https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [1]:
import numpy as np 
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3,4))
np.random.random(size=(3,4))

array([[0.91233092, 0.05461806, 0.46852974, 0.2745661 ],
       [0.45780857, 0.2494766 , 0.9058563 , 0.54418391],
       [0.90761004, 0.76599693, 0.9579623 , 0.04484562]])

In [3]:
from numpy.random import normal

normal_value = normal(size=(3,4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype


dtype('float64')

In [4]:
#ndarray,陣列運算
normal_value * 10

array([[-0.44849482, -1.72333302,  4.34986713, -5.05755783],
       [-7.61802427,  8.96614409, 11.42284404,  2.47220304],
       [-3.20526185, -2.68677762, -0.35236787, -0.83142169]])

In [5]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-0.28795185,  1.52431669, -0.7075829 ])